config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: "registrations"}

  root to: "home#index"

  devise_scope :user do
    delete "/logout" => "devise/sessions#destroy"
    get "deletion" => "home#deletion"
    get "forgot_password" => "home#forgot_password"
  end

  resources :game, only: [:index]
  resources :comments, only: [:create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :login

  def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["username = :value OR lower(email) = lower(:value)", { :value => login }]).first
      else
      	conditions[:email].downcase! if conditions[:email]
        where(conditions.to_hash).first
      end
  end
  
  validates :username, presence: true, length: {maximum: 255}, uniqueness: { case_sensitive: false }, format: { with: /\A[a-zA-Z0-9]*\z/, message: "may only contain letters and numbers." }

  has_many :comments

  has_attached_file :avatar, styles: { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "Unknown.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource_or_scope)
    game_index_path
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password, :avatar) }
  end
end

app/controllers/custom_failure.rb
class CustomFailure < Devise::FailureApp
    def redirect_url
       root_path
    end

    # You need to override respond to eliminate recall
    def respond
      if http_auth?
        http_auth
      else
        redirect
      end
    end
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  before_action  :authenticate_user!

  def index
  end	

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def forgot_password
  end
  
  def deletion
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    game_index_path
  end

  def after_update_path_for(resource)
    edit_user_registration_path(resource)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/game/index.html.erb
<div class="container">

	<%= render :partial => "shared/navbar" %>

	<div class="row">
		<div class="content">

			<div class="col-xs-md-10 col-md-6">
				<div class="game_positioning">
					<div id="game"></div>
				</div>
			</div> 

			<div class="col-xs-md-12 col-md-push-3 col-md-4">
				<iframe  class="mani" title="Shoutbox" src="http://shoutbox.widget.me/window.html?uid=il7vk216" frameborder="2" scrolling="auto"></iframe>
			</div>

		</div>
	</div>

	<div class="row">
		<div class="bottom">

			<div class="col-md-4">
				<%= image_tag ("wasd.png") %>
				<h3>Player 1</h3>
			</div>

			<div class="col-md-4">
				<%= image_tag ("arrows.png") %>
				<h3>Player 2</h3>
			</div>

			<div class="col-md-4">
				<h3>RULES</h3>
				<ul>		
					<li><%= image_tag ("bird.gif"), class: "birdy" %>Avoid Orlandos</li>
					<li><%= image_tag ("bird.gif"), class: "birdy" %>Avoid Balls</li>
					<li><%= image_tag ("bird.gif"), class: "birdy" %>Don't touch the borders or the ground</li>
				</ul>
			</div>

		</div>
	</div>
		
</div>

app/views/home/deletion.html.erb
<div class="wrapper">

	<%= render :partial => "shared/navbar" %>

	<div class="side_column">
		<%= render :partial => "shared/profile_column" %>
	</div>

	<h2>You Sure About This Punk?</h2>
	
	<div class="right_side_profile">
		<p>You wont do it? NO BALLS</p><br>

		<%= button_to "DELETE MY ACCOUNT", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete, class: "deletion" %>
	</div>

</div>

app/views/home/forgot_password.html.erb
<div id="password_container">

	<div class="password_box">
		<h1>Forgot your password?</h1>
		
		<%= form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :post }) do |f| %>
		  <%= devise_error_messages! %>

		  <div class="field_email">
		    <%= f.label "email:", class: "emails" %>
		    <%= f.email_field :email, autofocus: true, class: "password_info" %>
		  
		    <%= f.submit "Reset Password", class: "reset_button" %>

		  	<%= link_to "Back", root_path, class: "back_button", class: "back_button" %>
		  </div>

		<% end %>
	</div>

	<%= render :partial => "shared/forgot_password" %>
	
</div>

app/views/home/index.html.erb
<div id="homewrapper">

	<h1>Flappy Little</h1>
	
	<%= render :partial => "shared/login" %>
	
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li>
          <%= value %>
        </li>
      </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name='viewport' content='user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, width=device-width, height=device-height, minimal-ui' />
		
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

	    <title>Flappy Little</title>
		 
	    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	    <%= csrf_meta_tags %>

	</head>
	<body>

		<div class="container">
			<%= render 'layouts/messages' %>
			<%= yield %>
		</div>
		
		<!-- SCRIPTS -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

		<script src="http://shoutbox.widget.me/v1.js" type="text/javascript"></script> 
		
	</body>
</html>

app/views/shared/_for_signup.html.erb
<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>


<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>


<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>


<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>


<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/shared/_forgot_password.html.erb
<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>


<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>


<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/shared/_login.html.erb
<div id="login_box">

  <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>

    <div class="field">
      <%= f.text_field :login, class: "login_field", placeholder: "Username or Email" %>
   
      <%= f.password_field :password, class: "login_field", placeholder: "Password", autocomplete: "off" %>

      <%= f.submit "Log in", class: "login_button" %>
    </div>

  <% end %>

  <div class="sclick">
    <%- if devise_mapping.registerable? && controller_name != 'registrations' %>

      <%= link_to "Sign up", new_registration_path(resource_name), class: "sbutton" %><br />

    <% end -%>
  </div>

  <div class="sclick">
    <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>

      <%= link_to "Forgot your password?", forgot_password_path(resource_name), class: "sbutton" %><br />
      
    <% end -%>
  </div>

  <%= render :partial => "shared/within_login" %>

</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand"><%= link_to "Flappy Little", game_index_path, class: "logo_nav" %></span>
    </div>

   
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">

        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
        </form>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-menu-hamburger fa-2g"></span><span class="caret"></span></a>

          <ul class="dropdown-menu">
          	<li><%= link_to "Profile Settings", edit_user_registration_path, class: "sbutton" %></li>

            <li><%= link_to('Log Out', logout_path, method: :delete, class: "sbutton") %></li>
          </ul>

        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_profile_column.html.erb
<div class="list-group">
  <%= link_to "Profile Settings", edit_user_registration_path, class: "list-group-item archive" %>
  
  <%= link_to "Account Deletion", deletion_path, class: "list-group-item" %>
</div>

app/views/shared/_within_login.html.erb
<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>


<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>


<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>